# Generated by Django 4.1.3 on 2022-12-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAdministrator',
            fields=[
                ('id_administrator', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProjectAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_project_attraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdminPassword',
            fields=[
                ('id_administrator_pwd', models.OneToOneField(db_column='id_administrator_pwd', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.tbladministrator')),
                ('normal_password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_admin_password',
                'managed': False,
            },
        ),
    ]
